# Generated by Django 4.1.2 on 2022-10-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_document_major_subject_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='imgUrl',
            field=models.CharField(default='', max_length=255),
        ),
    ]
