# Generated by Django 4.1.2 on 2022-10-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_subject_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.IntegerField(default=1, max_length=3),
        ),
    ]
