# Generated by Django 4.1.2 on 2022-10-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
