# Generated by Django 4.1.2 on 2022-10-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_document_id_alter_subject_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.IntegerField(default=1, max_length=100),
        ),
    ]
