# Generated by Django 4.1.2 on 2022-10-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='imgUrl',
            field=models.CharField(default='https://vcdn1-vnexpress.vnecdn.net/2019/06/04/Hoa1-6179-1559618180.jpg?w=0&h=0&q=100&dpr=2&fit=crop&s=L1c433SwHnT3vn1ZPXOhyQ', max_length=255),
        ),
    ]
