# Generated by Django 4.1.2 on 2022-12-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_document_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=0, upload_to=''),
        ),
    ]
