# Generated by Django 4.1.2 on 2022-12-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='imgUrl',
        ),
        migrations.RemoveField(
            model_name='document',
            name='link',
        ),
        migrations.RemoveField(
            model_name='document',
            name='size',
        ),
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
        migrations.RemoveField(
            model_name='document',
            name='subjectID',
        ),
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='userID',
        ),
    ]
