# Generated by Django 4.1.2 on 2022-12-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_remove_document_date_remove_document_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='imgUrl',
            field=models.CharField(default='https://vcdn1-vnexpress.vnecdn.net/2019/06/04/Hoa1-6179-1559618180.jpg?w=0&h=0&q=100&dpr=2&fit=crop&s=L1c433SwHnT3vn1ZPXOhyQ', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.IntegerField(default=1, max_length=3),
        ),
        migrations.AddField(
            model_name='document',
            name='subjectID',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.IntegerField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='userID',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
